service: ccicomp-server

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  stage: api
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1


custom:
  logRetentionInDays: 90
  secrets: ${ssm:/aws/reference/secretsmanager/ccicomp-server~true}
  serverless-offline:
    noPrependStageInUrl: true
  customDomain:
    domainName: api.ccicomp.com.br
    basePath: ''
    stage: api
    createRoute53Record: true
  includeDependencies:
    enableCaching: true

package:
  excludeDevDependencies: true
  individually: true

functions:
  backyArticle:
    handler: dist/main.handler
    timeout: 30
    environment: ${self:custom.secrets}
    events:
      - http: ANY /{proxy+}
      - http: ANY /
